### ISSUE TITLE
Element Sorting?

### ISSUE THREAD

**Issue by foxtail286** [davecaruso/elemental4#84] opened 2021-02-18 03:42 UTC
There are tons and tons of elements in the game, and finding elements gets really annoying. A way to sort or quickly get elements (without relying on search or Ctrl-F) would be extremely helpful, as whenever I want to make a new combination, it takes me 10 seconds just to find the elements.

**Comment by davecaruso** [comment] 2021-02-18 14:38
duplicate of #44

**Closed by davecaruso** 2021-02-18 14:38 UTC
