### ISSUE TITLE
Just remove the searchbar at this point

### ISSUE THREAD

**Issue by Plasmoxxie** [davecaruso/elemental4#88] opened 2021-03-05 18:05 UTC
The search bar will not stop forcing me to type in it. it is nearly impossible to make elements because of it. please just remove it.

**Comment by Plasmoxxie** [comment] 2021-03-05 18:05
Its really not useful anyway.

**Comment by davecaruso** [comment] 2021-03-05 19:33
duplicate of fixed bug #82. i can not reproduce this bug on the latest build, however i have noticed firefox not being able to search and safari not being able to open the game at all. those can be investigated later i guess.

**Closed by davecaruso** 2021-03-05 19:33 UTC
