### ISSUE TITLE
Fix the damn search bar!

### ISSUE THREAD

**Issue by Plasmoxxie** [davecaruso/elemental4#82] opened 2021-02-16 18:02 UTC
Every time I try to suggest a new element, The search bar keeps forcing me to type in it. It is impossible to make new elements at this point. The worst part? THE SEARCH BAR DOESNT EVEN WORK! Every time I try to type, It types 2 letters instead of 1. Please fix this...

**Comment by Nv7-GitHub** [comment] 2021-02-16 18:04
https://github.com/davecaruso/elemental4/pull/81 Its fixed over there - you can go to https://deploy-preview-81--elem4.netlify.app/ to play for now

**Comment by Plasmoxxie** [comment] 2021-02-16 18:07
Ok, Thank you!

**Comment by Filip9696** [comment] 2021-02-16 18:28
Do not use deploy previews for playing the game

**Comment by davecaruso** [comment] 2021-02-16 18:31
i made a huge oversight during testing and didnt bother checking anything. and even my fix didnt even work for the lack of testing. the issue is fixed now

**Closed by davecaruso** 2021-02-16 18:31 UTC
